build: データバック機能
koki-takishita/home-care-navi-front pull request #123
Opened 2022-06-08 05:41 UTC by tmhr0

## プルリクルール守ってね

[プルリクルール](https://docs.google.com/spreadsheets/d/1XXQGmsRkmIlOpTE6KN6sx6Uya4u_lGKgscMaRdBZDzA/edit#gid=0)

## やったこと

確認画面⇨入力画面でのデータバック機能実装

## やらないこと

- このプルリクでやらないことは何か？（あれば。無いなら「無し」で OK）（やらない場合は、いつやるのかを明記する。）

無し

## できるようになること（ユーザ目線）

 入力データを修正したい時、修正が楽になる

## できなくなること（ユーザ目線）

無し

## 動作確認

①入力画面で入力
http://localhost:8000/contacts/new

②『この内容で問い合わせる』でアクティブストレージのデータ登録確認

③『もどる』で入力フォームにデータが入っていることを確認

④『この内容で問い合わせる』⇨『送信する』で完了画面へ
アクティブストレージのデータが消えていることを確認

⑤メールキャッチャーで正常にメール機能も働いているか確認
http://localhost:1080

### Front 側

- fetch and checkout

```ruby
git fetch && git checkout origin/feature/contacts-data-back
```

### docker compose

- build

```ruby
docker-compose build
```

- コンテナ入る

```ruby
docker-compose exec web bash
```

- コンテナリスタート

```ruby
docker-compose restart
```

### Loom 手順

[手順動画](https://www.loom.com/share/d2725c1dcde441fb9ca0f0b6dea684e8)

## その他

[確認してほしいシナリオテスト]
㉔ 非ログイン状態で利用規約
㉖ 非ログイン状態でプライバシーポリシー

### 確認書類

シナリオテスト用
[テスト仕様書](https://docs.google.com/spreadsheets/d/12xMuHo1K8Fd7FIB7rqeioxdWmrWw7aYK4QZ_Clsfk5Q/edit#gid=1789577746)

2022-06-08 07:11 UTC, watasho358 submitted a review, later dismissed

2022-06-08 07:12 UTC, watasho358 reviewed
メソッド名testはよくないかも
```
test() {
      localStorage.removeItem('name')
      localStorage.removeItem('email')
      localStorage.removeItem('types')
      localStorage.removeItem('content')
    },
```

2022-06-08 07:13 UTC, suwonkun submitted a review, later dismissed
確認okです

2022-06-08 07:15 UTC, watasho358 reviewed
これって何か意味あります？
confirm.vue
```
mounted() {
    this.setParameter()
    if (localStorage.getItem('name')) {
      this.name = localStorage.getItem('name')
    } else {
      this.name = ''
    }
    if (localStorage.getItem('email')) {
      this.email = localStorage.getItem('email')
    } else {
      this.email = ''
    }
    if (localStorage.getItem('types')) {
      this.types = localStorage.getItem('types')
    } else {
      this.types = ''
    }
    if (localStorage.getItem('content')) {
      this.content = localStorage.getItem('content')
    } else {
      this.content = ''
    }
  },
```

2022-06-08 07:50 UTC, koki-takishita approved these changes

2022-06-08 07:50 UTC, koki-takishita commented on pages/contacts/new.vue
> +    const name = localStorage.getItem('name')
まとめるやつ
```ruby
const name    = localStorage.getItem('name')
const email   = localStorage.getItem('email')
const types   = localStorage.getItem('types')
const content = localStorage.getItem('content')
if (name != null && email != null && types != null && content != null) {
  this.form.name    = localStorage.getItem('name')
  this.form.email   = localStorage.getItem('email')
  this.form.types   = localStorage.getItem('types')
  this.form.content = localStorage.getItem('content')
}
```

2022-06-08 07:50 UTC, koki-takishita commented on pages/contacts/confirm.vue
> +    test() {
test() → removeItemFromLocalStorage()
[![Image from Gyazo](https://i.gyazo.com/6f808bd36f2618489253a3a2e87cf92d.png)](https://gyazo.com/6f808bd36f2618489253a3a2e87cf92d)

2022-06-09 03:05 UTC, watasho358 requested changes
フッターからお問い合わせ画面に行くと、大量のエラーがコンソール上に出ます
![image](https://user-images.githubusercontent.com/34031637/172755506-15983698-cf3a-4590-9a34-b88e6cb99b19.png)

2022-06-09 05:03 UTC, tmhr0 commented
> シナリオテスト・動作確認OK フッターからお問い合わせ画面に行くと、大量のエラーがコンソール上に出ます !

エラー修正したので、次のプルリク時に確認をお願いします。

2022-06-09 07:11 UTC, watasho358 commented
もどるボタン押した時にデータ取得できてません。
というか、そもそもローカルストレージに保存できてないです。仕様かわりました？

2022-06-09 07:22 UTC, koki-takishita approved these changes
動作ok
テストチェック完了

2022-06-09 07:22 UTC, koki-takishita commented on pages/contacts/confirm.vue
> +            @click="SendSuccessPage(), RemoveItemFromLocalStorage()"
今回は許容しますが、本来は`SendSuccessPage`メソッド内で`RemoveItemFromLocalStorage()`を呼び出すのが一般的かと

2022-06-09 07:22 UTC, watasho358 approved these changes
動作OK
テストOK

2022-06-09 07:31 UTC, merged