build: 問い合わせフォーム
koki-takishita/home-care-navi-front pull request #41
Opened 2022-05-10 07:15 UTC by tmhr0

## 例

[link](https://dev.classmethod.jp/articles/pull-request-template/)

## チケットへのリンク

- https://example.com

## やったこと
・お問い合わせフォーム：入力・確認・完了画面　作成
・画面遷移

## やらないこと
入力時のバリテーション機能

## できるようになること（ユーザ目線）

ユーザーが運営に問い合わせできる

## できなくなること（ユーザ目線）

無し

## 動作確認

フッターからの画面遷移を確認
各ボタンからの画面遷移を確認
スマホ・PCサイズでの画面確認

## その他

- レビュワーへの参考情報（実装上の懸念点や注意点などあれば記載）

<img width="1270" alt="問い合わせ：入力" src="https://user-images.githubusercontent.com/70782980/167570739-f90c231d-ad91-4725-ab16-388006651bb3.png">

<img width="1233" alt="問い合わせ：確認" src="https://user-images.githubusercontent.com/70782980/167570731-08efb10a-1a1a-4ab6-b449-aab87a7c82cf.png">

<img width="1221" alt="問い合わせ：完了" src="https://user-images.githubusercontent.com/70782980/167570670-c68d448e-8546-4736-a6b2-2c2491a4049a.png">

2022-05-10 07:17 UTC, suwonkun submitted a review, later dismissed

2022-05-10 07:26 UTC, watasho358 requested changes
フッターからお問い合わせに遷移しないので、修正お願いします。
`layout/application.vue`

2022-05-10 07:35 UTC, watasho358 requested changes
`contact/new.vue` で、クリックイベントsubmitを定義してないのでクリックイベント消してください。ターミナルでエラーが出ています。
`@click="submit"`

2022-05-11 00:31 UTC, watasho358 approved these changes

2022-05-11 01:04 UTC, koki-takishita commented
OKです

2022-05-11 01:30 UTC, suwonkun approved these changes

2022-05-11 02:10 UTC, koki-takishita approved these changes

2022-05-11 02:10 UTC, merged