Feature/display error msg
koki-takishita/home-care-navi-front pull request #45
Opened 2022-05-13 02:04 UTC by koki-takishita

## やったこと
1. 新規登録画面スタイリング スマホ・PC対応
2. かぶっているスタイルファイル削除

## 動作確認
現在API側のプログラムの関係でバリテーションが2重になってしまうため、`app/model/user.rb`を下記と同じにしてからリクエストを送ってください
```ruby
class User < ApplicationRecord

  enum user_type: { customer: 0, specialist: 1 }
            # Include default devise modules.

  # Include default devise modules.

  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable,
          :confirmable
  include DeviseTokenAuth::Concerns::User

  validates :name, :phone_number, :post_code, :address, presence: true
  validates :phone_number,uniqueness: true

  def set_user_type(type)
    set_specialist if type == :specialist
  end

  def set_specialist
    self.specialist!
  end

=begin
  validates :name, :phone_number, :post_code, :address, :email, presence: true
  validates :email, uniqueness: true
=end

end

```
下記プルリクエストと同じ動作が出来る
[リンク](https://github.com/koki-takishita/home-care-navi-front/pull/44)

- レビュワーへの参考情報（実装上の懸念点や注意点などあれば記載）
追加で、ページの読み込み速度がおそすぎるので、それが改善バージョンをpushします。
まずはスタイリングのチェックお願いします

2022-05-13 05:50 UTC, suwonkun approved these changes
OKです

2022-05-15 03:28 UTC, watasho358 requested changes
フッターとカードの隙間がないので、修正お願いします。

![image](https://user-images.githubusercontent.com/34031637/168455865-ad0b66c6-a4cb-43ad-8044-e4220195a713.png)

2022-05-15 03:33 UTC, koki-takishita commented
> フッターとカードの隙間がないので、修正お願いします。
> 
> ![image](https://user-images.githubusercontent.com/34031637/168455865-ad0b66c6-a4cb-43ad-8044-e4220195a713.png)

2022-05-15 03:34 UTC, koki-takishita commented
@watasho358 
ミスって消してしまった..ごめんなさい
ローカルだと対応済みです

[![Image from Gyazo](https://i.gyazo.com/d9ca3ec5fa2add73b23e5f497e0e5ccf.png)](https://gyazo.com/d9ca3ec5fa2add73b23e5f497e0e5ccf)

[![Image from Gyazo](https://i.gyazo.com/b249480fe4f6b6cd2b51d34387a0691e.png)](https://gyazo.com/b249480fe4f6b6cd2b51d34387a0691e)

2022-05-15 03:35 UTC, watasho358 commented
了解です。先に僕のほうでプルリク投げます

2022-05-15 03:39 UTC, koki-takishita commented
> 了解です。先に僕のほうでプルリク投げます
申し訳ないんですが、休日に開発が当たり前になってしまうのは良くない気がします
気持ちはわかりますが、控えていただけますか？
個人的なキャッチアップと仕事で行う開発は切り分けていただきたいです
休日にプルリク上げてしまうと、他のメンバーに休日に働くことが当たり前な雰囲気は出したくないです
issuesは上げもらって構いませんが

2022-05-15 03:41 UTC, watasho358 commented
了解です。気をつけます

2022-05-15 03:47 UTC, koki-takishita commented
> 了解です。気をつけます
すみませんが、お願いします
僕の作業とかぶらなそうなら、上げてもらって構わないです。
月曜朝いちでプルリク更新するのでそれで判断してください

2022-05-15 03:47 UTC, koki-takishita commented
> > 了解です。気をつけます

すみませんが、お願いします
僕の作業とかぶらなそうなら、上げてもらって構わないです。
月曜朝いちでプルリク更新するのでそれで判断してください

2022-05-16 02:03 UTC, suwonkun approved these changes
OK

2022-05-16 02:07 UTC, watasho358 approved these changes

2022-05-16 02:39 UTC, tmhr0 approved these changes
機能確認OKです。
プルリク更新後のレイアウト確認もOKです。

2022-05-16 02:39 UTC, merged