build: login機能実装 フラッシュメッセージは無し
koki-takishita/home-care-navi-front pull request #53
Opened 2022-05-17 01:41 UTC by koki-takishita

## やったこと

1. ログイン処理 ロジック `plugins/login.js`
2. ログアウト処理 ロジック 
3. ログイン・ログアウトそれぞれ共通の関数化
    - ログイン処理  `plugins/login.js`
    - ログアウト処理 `plugins/logout.js`

## 関数化した意図
- 下記がログイン・ログアウトのロジック
```js
  $axios.onRequest((config) => {
    config.headers.client = window.localStorage.client
    config.headers['access-token'] = window.localStorage.getItem('access-token')
    config.headers.uid = window.localStorage.uid
    config.headers.expiry = window.localStorage.expiry
  })

  $axios.onResponse((response) => {
    console.log(`[LOG]::onResponse::${response}`)
    store.commit('catchErrorMsg/clearMsg')
    const headers = response.headers
    if (
      headers.client &&
      headers.uid &&
      headers.expiry &&
      headers['access-token']
    ) {
      localStorage.setItem('access-token', headers['access-token'])
      localStorage.setItem('client', headers.client)
      localStorage.setItem('uid', headers.uid)
      localStorage.setItem('expiry', headers.expiry)
    }

export default function ({ $auth, redirect }, inject) {
  inject('login', (loginInfo) => {
    login(loginInfo)

    async function login(loginInfo) {
      try {
        const response = await $auth.loginWith('local', {
          data: loginInfo,
        })
        redirect('/top')
        return response
      } catch (error) {
        return error
      }
    }
  })
}

export default function ({ $auth }, inject) {
  /* eslint-disable */
  inject('logout', (tmp) => {
    logout($auth)

    async function logout(auth) {
      try {
        const response = await auth.logout()
        authDataDeleteToLocalStorage()
        return response
      } catch (error) {
        return error
      }
    }

    function authDataDeleteToLocalStorage() {
      localStorage.removeItem('access-token')
      localStorage.removeItem('expiry')
      localStorage.removeItem('client')
      localStorage.removeItem('uid')
    }
  })
}
```
- 上記のようなロジックを直接ページに書くのはみづらすぎる
- 下記のように関数化することでスッキリする
```js
methods: {
  login() {
    this.$login(this.loginInfo)
  },
  logout() {
    this.$logout(this.loginInfo)
  },
},
```
ログイン・ログアウトで変更があったら処理ごとに見ればいいので、スコープが狭められる
- `plugins/login.js`
- `plugins/logout.js`
- `plugins/axios.js`
## やらないこと

1. ログイン・ログアウト成功時、失敗時のメッセージはまた改めて出します
2. ログアウトボタンはとりあえず、TOPページに配置してます、改めて下記のような実装にします
    - ログイン後headerにログアウトボタン表示
    - ログイン後: 予約・閲覧・お礼・ブックマーク・登録情報をログイン後に表示
    - ログインしてないと上記の項目は表示しない

## できるようになること（ユーザ目線）

ログインできる

## できなくなること（ユーザ目線）

ログアウトできる

## 動作確認

1. 有効済みのアカウントを用意する
2. ログインページからログインする
3. ログインできていることを確認する(localstorageにデータが保持されている状態) 動画参照
4. ページをリロードしてもログイン状態が維持されていることを確認する
5. ログアウトボタンでログアウトできていることを確認する(localstorageにデータがないこと)
[手順動画](https://www.loom.com/share/92abb1a5c0694376bd953f7700b0950b)

## 追加分
1. エラー対応(401 422)
2. ログイン・ログアウトヘッダー対応
- 未認証のユーザー(エラーメッセージにはメール送ったとありますが、現在メール届かない感じです また後日対応します)
```ruby
'foobar@example.com' に確認用のメールを送信しました。メール内の説明を読み、アカウントの有効化をしてください
```
- 組み合わせが不正なもの
```ruby
ログイン用の認証情報が正しくありません。再度お試しください。
```
- APIサーバーと接続できない時
```ruby
送信ができませんでした。しばらく経ってから再度お願いします。
```
[手順動画 エラーメッセージ](https://www.loom.com/share/c6458893bb8f4653af429088787c6de4)
[手順動画 ヘッダー切替対応](https://www.loom.com/share/313be485b4e94200a88674d8d2c04024)
明日以降
- 成功系をやります
ログイン成功したらログインしました表示
loomはマージされたら消します

2022-05-17 06:51 UTC, koki-takishita commented
- 追加分
1. エラー対応(401 422)
- 未認証のユーザー(エラーメッセージにはメール送ったとありますが、現在メール届かない感じです また後日対応します)
```ruby
'foobar@example.com' に確認用のメールを送信しました。メール内の説明を読み、アカウントの有効化をしてください
```
- 組み合わせが不正なもの
```ruby
ログイン用の認証情報が正しくありません。再度お試しください。
```
- APIサーバーと接続できない時
```ruby
送信ができませんでした。しばらく経ってから再度お願いします。
```
[手順動画](https://www.loom.com/share/c6458893bb8f4653af429088787c6de4)

明日以降
- 成功系をやります
ログイン成功したらログインしました表示

2022-05-17 07:28 UTC, watasho358 requested changes
ログインボタンを押しても何も起きず、ローカルストレージにデータが保存されないのと、トップページにログアウトボタンがありません。
![image](https://user-images.githubusercontent.com/34031637/168753656-75f4cab5-20e6-41c4-8440-c90c44e8da57.png)
![image](https://user-images.githubusercontent.com/34031637/168753748-63c38330-95ea-4b52-a185-37a64663e2c5.png)
![image](https://user-images.githubusercontent.com/34031637/168754087-35984d47-0d7a-4e90-875e-07d6dcdf8e0d.png)

2022-05-17 07:30 UTC, koki-takishita commented
ログインボタン押したときのネットワークタブ見せてください

2022-05-17 07:31 UTC, koki-takishita commented
この前と動揺に下記のコマンドお願いします
`docker-compose restart`

2022-05-17 08:09 UTC, watasho358 approved these changes

2022-05-18 02:15 UTC, suwonkun approved these changes
OKです

2022-05-18 02:46 UTC, tmhr0 approved these changes
確認OKです。感謝。

2022-05-18 02:46 UTC, merged